name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: crowdsec-helper-service
      APP_VERSION: ${{ github.ref_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'

      - name: Build application
        run: make build VERSION=${{ env.APP_VERSION }}

      - name: Pack binary
        run: tar -czvf ${{ env.APP_NAME }}-${{ env.APP_VERSION }}.tar.gz ./bin/${{ env.APP_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: |
            ${{ env.APP_NAME }}-${{ env.APP_VERSION }}.tar.gz

